"""add_refresh_tokens_indexes_and_enums

Revision ID: 590386efd54b
Revises: ba6a9c980fea
Create Date: 2026-07-29 21:49:48.882265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590386efd54b'
down_revision: Union[str, None] = 'ba6a9c980fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
